Repository ExpTechTW/TREM-tauri, pull requests merged in 2024-02, with the labels that each got.

#7 Update build.yml
  .github/workflows/build.yml
Labels: size/XS

#8 fix; wave radius on get ntp
  src/main.ts
Labels: size/XS

#6 fix: wave timer reset
  src/main.ts
Labels: size/XS

#9 chore: SystemTray tooltip
  src-tauri/src/main.rs
Labels: size/XS

#10 feat: nsspe support
  src/components/component/CrossMarker.vue
  src/components/component/DotMarker.vue
  src/components/component/EEW.vue
  src/components/component/MapEew.vue
  src/main.ts
  src/scripts/class/api.ts
  src/styles/intensity.css
  src/types.ts
Labels: size/L, ✨ Feature

#11 fix: intensity not being updated
  src/components/component/EewIntensity.vue
Labels: 🐛 Bug, size/XS

#14 feat: auto resize markers based on map zoom
  src/components/component/EEW.vue
  src/components/component/MapReportListMarker.vue
  src/scripts/helper/constant.ts
  src/scripts/helper/utils.ts
Labels: ✨ Feature, size/M

#12 fix: info box showing wrong detail with nsspe
  src/components/component/DotMarker.vue
  src/components/component/MapRtsBox.vue
  src/components/component/RtsMarker.vue
  src/components/view/InfoBox.vue
  src/styles/intensity.css
  src/types.ts
Labels: 🐛 Bug, size/M

#15 fix: region file
  public/map/tw_town.json
  src/assets/json/code.json
  src/assets/json/region.json
  src/components/view/InfoBox.vue
Labels: size/XS

#16 feat: home view components
  .github/workflows/build.yml
  package-lock.json
  package.json
  src/App.vue
  src/assets/json/code.json
  src/assets/json/default_config.json
  src/components/component/DetailedReportItem.vue
  src/components/component/FilledButton.vue
  src/components/component/IntensityBox.vue
  src/components/component/LocalRtsBox.vue
  src/components/component/MapReportMarker.vue
  src/components/component/ReportItem.vue
  src/components/component/RtsMarker.vue
  src/components/view/HomeView.vue
  src/components/view/MapView.vue
  src/components/view/ReportBox.vue
  src/components/view/ReportListBox.vue
  src/main.ts
  src/styles.css
  src/styles/font.css
  src/types.ts
Labels: size/XL

#17 fix: local rts box
  src/components/component/LocalRtsBox.vue
  src/main.ts
Labels: size/XS

#19 Fix/report magnitude depth color
  src/components/component/DetailedReportItem.vue
  src/components/component/LocalRtsBox.vue
  src/components/component/ReportDetailField.vue
  src/components/component/WaveTimer.vue
  src/components/view/HomeView.vue
  src/components/view/MapView.vue
  src/components/view/ReportBox.vue
  src/scripts/helper/color.ts
  src/styles.css
Labels: 🐛 Bug, size/M

#18 feat: override area intensity
  src/components/component/EewIntensity.vue
  src/components/component/MapEewIntensity.vue
  src/components/view/MapView.vue
  src/scripts/class/api.ts
Labels: 💪 Enhancement, size/M

#23 fix: route rts
  src/scripts/class/api.ts
Labels: 💪 Enhancement, Confirmed, size/XS

#24 feat: copy report
  .eslintrc
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/tauri.conf.json
  src/components/component/ChipButton.vue
  src/components/view/ReportBox.vue
Labels: size/L, ✨ Feature

#22 feat: always on top
  src/assets/json/default_config.json
  src/main.ts
  src/scripts/class/api.ts
Labels: ✨ Feature, size/M

#25 chore: release actions
  .github/workflows/release.yml
Labels: size/M

#27 Release v0.0.0-alpha.2
  .eslintrc
  .github/workflows/release.yml
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/tauri.conf.json
  src/assets/json/default_config.json
  src/components/component/ChipButton.vue
  src/components/view/ReportBox.vue
  src/main.ts
  src/scripts/class/api.ts
Labels: size/L, 🪄 Release

#30 feat: startup with system
  CHANGELOG.md
  package-lock.json
  package.json
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/src/main.rs
  src-tauri/tauri.conf.json
  src/assets/json/default_config.json
  src/main.ts
  src/types.ts
Labels: size/L, ✨ Feature

#28 fix: report copy null check
  src/components/view/ReportBox.vue
Labels: 🐛 Bug, size/S

#31 fix: disable edge webview keybinds
  CHANGELOG.md
  src/main.ts
  src/styles.css
Labels: 🐛 Bug, size/M

#32 feat: auto updates report lists
  CHANGELOG.md
  src/main.ts
Labels: 💪 Enhancement, size/S

#33 fix: map disappearing
  src/components/component/MapEew.vue
  src/components/view/HomeView.vue
  src/components/view/MapView.vue
  src/main.ts
Labels: 🐛 Bug, size/M

#34 fix: mapview missing element reference
  CHANGELOG.md
  src/App.vue
  src/components/view/MapView.vue
Labels: 🐛 Bug, size/S

#35 chore: more specific on font imports
  src/styles/font.css
  vite.config.ts
Labels: 💪 Enhancement, size/S

#36 fix: map broken when view changed
  src/components/component/CircleMarker.vue
  src/components/component/MapEew.vue
  src/components/view/HomeView.vue
  src/components/view/MapView.vue
  src/main.ts
Labels: 🐛 Bug, size/M

#39 fix: issue template
  .github/ISSUE_TEMPLATE/bug-issue.yml
Labels: size/XS

#40 chore: changelog
  .github/ISSUE_TEMPLATE/bug-issue.yml
  CHANGELOG.md
Labels: size/S

#43 hotfix: release.yml workflow
  .github/workflows/release.yml
Labels: size/XS

#44 hotfix: release workflow
  .github/workflows/release.yml
Labels: size/XS

#49 fix: check config path exists
  src-tauri/capabilities/desktop-capability.json
  src/App.vue
  src/components/view/HomeView.vue
  src/components/view/MapView.vue
  src/components/view/ReportBox.vue
  src/main.ts
  src/scripts/class/config.ts
Labels: 🐛 Bug, size/M, priority: 0

#48 fix: logging category
  .github/ISSUE_TEMPLATE/bug-issue.yml
  src-tauri/src/lib.rs
  src/scripts/class/api.ts
  src/scripts/class/config.ts
Labels: 🐛 Bug, size/M

#50 feat: https fetch
  .github/ISSUE_TEMPLATE/bug-issue.yml
  CHANGELOG.md
  src/App.vue
  src/scripts/class/api.ts
  src/scripts/class/route.ts
Labels: 💪 Enhancement, size/L

#52 feat: version display & tauri upgrade
  CHANGELOG.md
  package-lock.json
  package.json
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/assets/TOS
  src-tauri/assets/terms.rtf
  src-tauri/capabilities/desktop-capability.json
  src-tauri/src/lib.rs
  src-tauri/tauri.conf.json
  src/components/component/NavigationBar.vue
  src/main.ts
  src/scripts/class/api.ts
Labels: size/L

#53 feat: support cancellation
  CHANGELOG.md
  public/audio/cancel.wav
  src/App.vue
  src/components/component/EEW.vue
  src/components/view/HomeView.vue
  src/types.ts
Labels: ✨ Feature, size/M

#54 chore: dump version to 0.0.0-alpha.4
  package-lock.json
  package.json
Labels: size/XS

#55 release: v0.0.0-alpha.4
  .github/ISSUE_TEMPLATE/bug-issue.yml
  CHANGELOG.md
  package-lock.json
  package.json
  public/audio/cancel.wav
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/assets/TOS
  src-tauri/assets/terms.rtf
  src-tauri/capabilities/desktop-capability.json
  src-tauri/src/lib.rs
  src-tauri/tauri.conf.json
  src/App.vue
  src/components/component/EEW.vue
  src/components/component/NavigationBar.vue
  src/components/view/HomeView.vue
  src/components/view/MapView.vue
  src/components/view/ReportBox.vue
  src/main.ts
  src/scripts/class/api.ts
  src/scripts/class/config.ts
  src/scripts/class/route.ts
  src/types.ts
Labels: size/XL, 🪄 Release
